# -*- coding: utf-8 -*-
"""S25015430_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZdPTd4ATtnxzEvgTzqf1GIwnlSjpXIY_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LinearRegression
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Dropout

df = pd.read_csv("/content/drive/MyDrive/Advance Machine Learning task 1/Iris.csv")

print(df.head())
print(df.info())

from google.colab import drive
drive.mount('/content/drive')

if 'Id' in df.columns:
    df = df.drop('Id', axis=1)
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
X = df.drop('Species', axis=1)
y = df['Species']
scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

# Convert to class labels (0,1,2)
y_pred_lr_class = np.round(y_pred_lr).astype(int)
y_pred_lr_class = np.clip(y_pred_lr_class, 0, 2)

print("Linear Regression Accuracy:", accuracy_score(y_test, y_pred_lr_class))
print("\nClassification Report (LR):")
print(classification_report(y_test, y_pred_lr_class))

X_train_rnn = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_rnn = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

model = Sequential()

model.add(SimpleRNN(32, activation='tanh', input_shape=(1, X_train.shape[1])))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))  # 3 classes

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train_rnn, y_train,
    epochs=20,
    batch_size=16,
    validation_data=(X_test_rnn, y_test),
    verbose=1
)

y_pred_rnn = model.predict(X_test_rnn)
y_pred_rnn_class = np.argmax(y_pred_rnn, axis=1)

print("RNN Accuracy:", accuracy_score(y_test, y_pred_rnn_class))

print("\nClassification Report (RNN):")
print(classification_report(y_test, y_pred_rnn_class))

plt.figure()
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("RNN Loss (Iris)")
plt.legend()
plt.show()

cm = confusion_matrix(y_test, y_pred_rnn_class)

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix (Iris)")
plt.colorbar()
for i in range(len(cm)):
    for j in range(len(cm[0])):
        plt.text(j, i, cm[i][j], ha='center', va='center')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

plt.figure()
df['Species'].value_counts().plot(kind='bar')
plt.title("Class Distribution")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()

plt.figure()
sns.heatmap(pd.DataFrame(X, columns=df.drop('Species', axis=1).columns).corr(),
            annot=True, cmap='coolwarm')

plt.title("Feature Correlation Heatmap")
plt.show()

pd.DataFrame(X, columns=df.drop('Species', axis=1).columns).hist(figsize=(10,8))
plt.suptitle("Feature Distributions")
plt.show()

df_plot = df.copy()
df_plot['Species'] = le.inverse_transform(df_plot['Species'])
sns.pairplot(df_plot, hue='Species')
plt.show()

plt.figure()
plt.plot(y_pred_rnn[:20], label='Predicted Probabilities')
plt.title("RNN Prediction Probabilities (First 20)")
plt.legend()
plt.show()

plt.figure()
plt.plot(y_test.values[:20], label='Actual')
plt.plot(y_pred_rnn_class[:20], label='Predicted')
plt.title("Actual vs Predicted (First 20)")
plt.legend()
plt.show()

acc_lr = accuracy_score(y_test, y_pred_lr_class)
acc_rnn = accuracy_score(y_test, y_pred_rnn_class)
plt.figure()
plt.bar(["Linear Regression", "RNN"], [acc_lr, acc_rnn])
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.show()